version: 2
jobs:
  one:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
  two:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Take screenshot
          command: npm start

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
